### PR TITLE
Home page refactor

### PR DESCRIPTION
**Pull request by dfabulich**
* Made "New on IFDB" show only site news, polls, competitions, and lists over the prior three days.
* Enabled images
* Added "Games" and "Reviews" sections
    * Games links to browse pages: New, Top, Hot (Highest Rated in the last 60 days), Random, Unreviewed
* Added Competitions and Lists sections 
* Removed "control panel" side pane
    * Added Search links to Games, Lists, Polls, Competition sections
    * Added "Admin" link to "Welcome to IFDB" header
    * Converted "Top Reviewers", "IF Links" and "In the Database" ("Database Stats") into sections of the main page
* Added Table of Contents links at the top, making it easy to scroll down to each section (e.g. on mobile)

TODO
* Delete unused icon files and CSS rules (I'll do this in a subsequent PR so I can start making small PRs instead of a giant one)
* Minor polish fixes

# Before
before
# After
shippable

### CODE REVIEW

**Comment by salty-horse** [comment]
Both the current home page and this one should have a section specifically aimed at newcomers. Maybe something that leads them to recommended "first" games, or popular games, with instructions on how to find the "Play online" button, and a "New to IF" guide, including explanations of the various kinds (Parser / hypertext, etc) and what they require from the player (e.g., typing)

**Comment by dfabulich** [comment]
We discussed it a some here https://intfiction.org/t/changes-on-deck-on-dev-ifdb-org-2024-10-30-home-page-refactor/72074 and more here https://intfiction.org/t/an-idea-split-game-and-review-feeds-on-ifdb/66710/17?u=dfabulich

**Comment by dfabulich** [comment]
I think I want to merge this and do additional fixes in PRs.

Responding to feedback:

> 1. The links at the top that replace the sidebar (with "Games", "Reviews", "Polls", ...) should be more prominent. Maybe they should have the same background as the sidebar? Same goes for the links under the "More Games" heading.

Agreed; I'll do that in a separate PR.

> 2. It's weird that to add a new game you have to click "Games" at the top, and find the "Add a game listing" in the "More Games" section.

The section is no longer called "More Games," it's just "Games," now that "New on IFDB" no longer includes games or reviews.

Similarly, item 3 is obsolete; "New on IFDB" no longer has game listings in it.

> 4. For a website that newcomers might find, it needs to be less scary - a wall of text with no images doesn't feel like welcoming, and the sidebar helped break that up, and guide the first-time visitor. Sections should the icons that were in the sidebar.

The feedback I saw on the forum is that folks do not miss those sidebar icons at all. I'm open to a follow-up PR in which someone cooks new icons for this, but the old ones just were no good at all.

> 4a. Games in the "More Games" section should have covers, like in the recommendations section.

Done

> 4b. Also, there should be an easier way to "Browse games" and see the top games. There's a "Browse" at the header, but it doesn't catch the eye.

The "Games" section has pretty good links now: New, Top, Hot, Random, Unreviewed, Advanced Search.

I'm open to making it more eye catching in a follow-up PR, but I don't know what would be appropriate.

Item 5 is obsolete; the sections are now "Games" and "Reviews" and not "More Games" and "More Reviews."

> 6. It should be clearer what each section's sorting is. For "New on IFDB" it's clear from the title, for the others, less so. See the [BoardGameGeek Dashboard](https://boardgamegeek.com/dashboard) where each section has its sorting in the title.

I think we can do that in a follow up PR, but I'm not exactly sure how to do it. I'd like to leave the sections named "Games" and "Reviews", and I'm not sure I want to add a sorting dropdown to the section headers; it feels overcomplicated.

> 7. In the "Polls" section, the "see more" is above the list of polls. In the other section, it's at the bottom of the list.

The Polls section, unlike the other sections, has two subsections: new polls, and polls with recent votes. It has two "See More" links, one for each subsection. It also has a "Browse all polls" link which sorts by most votes.

It's complicated, but it's not clear that moving the "See More" links to the bottom will make it better, because that would juxtapose the the "See more" link (sort by recently voted) next to the "Browse all polls" link (sort by most votes).

> Both the current home page and this one should have a section specifically aimed at newcomers. Maybe something that leads them to recommended "first" games, or popular games, with instructions on how to find the "Play online" button, and a "New to IF" guide, including explanations of the various kinds (Parser / hypertext, etc) and what they require from the player (e.g., typing)

That is what the "New to IF?" section is for, but it's not doing anything useful right now. (At least it's no _worse_ in this PR than it is in the old home page.) In a few months, my plan is to do an IFDB Award for "Games for beginners" and put the winning games in the "New to IF?" section. #415

**Comment by salty-horse** [comment]
Should I post my comments there? Do you want to deploy this and iterate on it later?

**Comment by dfabulich** [comment]
I think I will deploy this; let's track follow up points as Github issues.

**Pull request merged**
