### PR TITLE
Mobile dropdown menu

### PR DESCRIPTION
**Pull request by Iniquit**
This PR converts the main nav menu into a dropdown/hamburger menu on small screen sizes.

Before / after / after (expanded):
<div style="display:flex">

</div>
<br>
Closes iftechfoundation/ifdb-suggestion-tracker/issues/252

### CODE REVIEW

**Comment by dfabulich** [comment]
Sorry to leave this PR waiting so long. I have some thoughts about this PR.

1. When I use Chrome Dev Tools and emulate a mobile device, it defaults to emulating a Moto G4, 360x640; the layout isn't correct in that case. (It's also broken on the small sized iPhone SE.)
    localhost_8080_(Moto G4)
2. Taking a harder look at the menu, most of the menu items don't work unless you're logged in. (Profile, Settings, My Activity, Inbox, Log Out). The only ones that do work when you're logged out are Home, Browse, "Search" (which links to a documentation page describing advanced search filters) and Log In.

    * I think maybe we should remove the "Search" documentation link entirely on mobile. (Maybe even remove it on desktop, too? Perhaps just link to the "search tips" documentation page from a "tipbox" on the search results page?)
    * The banner itself is a home link, so I think we can remove "Home" entirely, too, at least on mobile.
    * If we do that, we could replace the menu with a "Log In" link when you're logged out. The banner menu would then just say "Log In" "Browse" "[Search for games… 🔍]" and when you're signed in, it would say "≡ Menu" "Browse" "[Search for games… 🔍]"
3. I think it's a bit odd that the menu expands inside the grey header bar. I think it's more typical to have the menu pop up an overlay over the content, or to slide in from the side or top of the screen.

    For example, IMDb has two menus when you're logged in, a ≡ "hamburger" menu icon, followed by a small site logo (which links to the home page), then a search button, and finally either a "Sign In" link, or, if you're signed in, an "Account Menu" button. If you click the hamburger menu, it slides in a menu from the side; if you click the "account" menu, it pops up an overlay.

Despite these quibbles, I think this is still an improvement over what we have, and so I'd merge it if only the first issue (layout on small phones) gets fixed.

**Review by dfabulich — CHANGES_REQUESTED** [review]
I made comments back in June for this PR filed in April. 😖 I'll probably just jump in and make changes myself to apply this PR in the next month or two if you don't get around to it firsrt.

**Comment by Iniquit** [comment]
Thanks! Sorry, things have been a little crazy lately and I've neglected to get back to this. I'll tackle the immediate small-screen-size layout issue this week.

2 and 3 are good points and seem like they would make the menu easier to use! (I'm not 100% sure how to implement them myself but I'll take a look while I'm addressing 1, just in case.)

**Comment by Iniquit** [comment]
All right! A quick overview of the new version is below. I didn't get to 3 and the slide-out menu, but most of 2 should be incorporated:

**Mobile** 
Logged out / logged in / logged in (expanded):
<div style="display:flex">



</div>
<br>

**Desktop:**
Logged out / logged in:
<div style="display:flex">


</div>

And there's one behavioral change: clicking the login link in the top menu and logging in now returns the user directly to the homepage afterwards instead of showing them an interstitial "You're logged in now" page.

**Comment by dfabulich** [comment]
Thanks! I'm going to merge this and then file another PR with additional changes for you to look at

**Pull request merged**
