### PR TITLE
Do not leak unwishlist info for games

### PR DESCRIPTION
**Pull request by salty-horse**
The "unwishlist" count was previously removed from the game page, but it was still returned in the API response.

If this information shouldn't be available, it should also be scrubbed from the database dump.

### CODE REVIEW

**Comment by dfabulich** [comment]
That data is not private AFAIK. (But maybe it ought to be?)

https://ifdb.org/whoselist?game=uaxh30z0kh7n8nt3&type=unwishlist

**Comment by alice-blue** [comment]
On the settings page, there is a "Public Play Lists" section with checkboxes so that people can decide whether to make their play list / wish list / not interested list public or not

**Comment by dfabulich** [comment]
Oh, yeah, I forgot about that! It looks like they aren't getting scrubbed from the DB properly. 😖 There are 18K unwishlists in the production DB, and 13K unwishlists in the backup.

**Comment by dfabulich** [comment]
As for this PR, I think it makes sense to show the count of public unwishlists in the API. I don't know if it's actually _doing_ that or not…?

**Comment by salty-horse** [comment]
It's not returned in the public API, but it's available in the [whoselist](https://ifdb.org/whoselist?game=aearuuxv83plclpl&type=unwishlist) page, that is not linked from anywhere.

I'm OK with leaving this as-is (I think youtube's video pages still tell you how many thumbs down a video has, even though it's not displayed), but I don't like `setunwishlist` counting and returning something that's unused. Is it ok to merge if I reword the commit message?

**Comment by dfabulich** [comment]
Yeah, that should be fine

**Comment by salty-horse** [comment]
Committed as 7a9e775be6991bcadffe2e5837c2cf306cd6d113

**Pull request closed without merging**
