### PR TITLE
Improve viewgame layout in standards mode

### PR DESCRIPTION
**Pull request by salty-horse**
Fixes the cover art issue mentioned here https://github.com/iftechfoundation/ifdb/issues/646#issuecomment-2466082560, setting the game page header with an explicit width, instead of placing it inside a `<p>`, which is not supported.

I checked both the main page view, and specific modes like `&reviews`. It looks fine in both.

The header is now a `<section>`. Semantically, I think the review counts and playtime rows should be part of it, but the current code structure makes it difficult/less readable.

### CODE REVIEW

**Comment by dfabulich** [comment]
I'm having a hard time reproducing the bug that you're fixing.

In https://github.com/iftechfoundation/ifdb/issues/646#issuecomment-2466082560 you wrote:

> This can be seen in:
> 
> * The [File Formats](https://ifdb.org/fileformat) page, where the text extends far beyond `max-width` set by the `<p>` it's  in. Also, in standards mode, tables aren't allowed in `<p>`, so
> * The game page, where the covert art is further to the right than the rest of the text.

The file format page looks fine to me. And I see no visible effect on the games page. (But maybe the point is that this only fixes a bug that _would_ crop up in `<!doctype html>` mode…?)

image

**Review by dfabulich — COMMENTED** [review]
Requested clarification

**Comment by salty-horse** [comment]
Yes, this is fixing problems that appear when turning on Standards mode. I'm fixing them in advance, so it can be turned on for all pages at once.

Have two tabs open side-by-side, turn it on in one of them, and compare.

**Comment by salty-horse** [comment]
This broke the style of the tag editor. Fixed in 79a0523d6213836216d7787bfc63de56dd2c91c8.

**Comment by salty-horse** [comment]
This also broke spacing between the "External Links" and "Have you played this game?" sections. Checking...

**Pull request merged**
