### PR TITLE
Don't update `reviews.moddate` when updating `embargopastdate`

### PR DESCRIPTION
**Pull request by dfabulich**
Fixes https://github.com/iftechfoundation/ifdb-suggestion-tracker/issues/428

### CODE REVIEW

**Comment by dfabulich** [comment]
This bug is messing up `moddate` for a bunch of reviews, so I'm just going to merge it now.

**Comment by salty-horse** [comment]
I don't understand what setting `moddate` to its own value is doing.

**Comment by dfabulich** [comment]
`moddate` automatically updates itself to `now()`, unless you manually set it to something. Setting it to its own old value prevents it from changing, which is what we need in this case.

**Comment by salty-horse** [comment]
Maybe a comment explaining it would help...? Unless it's obvious and I'm silly.

**Pull request merged**
