### PR TITLE
Prevent mobile browser zoom

### LINKED ISSUE #1057: Prevent mobile browser zoom on login form
On iOS, when you go to the login page, we autofocus the "Email address" field, and the browser zooms in slightly. That's annoying.

https://stackoverflow.com/a/6394497/54829

> The browser will zoom if the font-size is less than 16px and the default font-size for form elements is 11px (at least in Chrome and Safari).

### PR DESCRIPTION
**Pull request by dfabulich**
Fixes #1057

Just getting started, because to actually fix most forms, we have to redesign them so the field label appears above the field, instead of in a table cell to the left.

### CODE REVIEW

**Review by salty-horse — APPROVED** [review]

**Comment by dfabulich** [comment]
Now login and review forms work. A few other forms luckily started working just from setting all inputs to 16px.

**Comment by salty-horse** [comment]
The two links above the review box used to be aligned with its right edge, and now they moved to the right.
review

**Comment by dfabulich** [comment]
Hrm. This seems to vary by browser.

**Comment by dfabulich** [comment]
Fixed the review page, tested in Firefox, Chrome, and Safari.

**Pull request merged**
