### PR TITLE
search: Make `played:yes` filter include games you've reviewed/rated

### PR DESCRIPTION
**Pull request by dfabulich**
Fixes https://github.com/iftechfoundation/ifdb-suggestion-tracker/issues/494

### CODE REVIEW

**Comment by salty-horse** [comment]
I wonder if it should work differently, where rating a game will also mark it as "played", with a flag that it was done automatically due to a rating.

And delete all ratings/reviews for a game, it should check if "played" was an automatic marking, and delete that too.

**Review by salty-horse — APPROVED** [review]

**Comment by salty-horse** [comment]
Does it make sense to have a separate `reviewed:yes` query to only search games you're reviewed?

**Comment by dfabulich** [comment]
I'm unsure what the right approach is; I opened a thread about it on the intfiction forum here. https://intfiction.org/t/ifdb-played-yes-and-ratings-reviews/71269

**Comment by dfabulich** [comment]
I'm closing this out, in favor of https://github.com/iftechfoundation/ifdb-suggestion-tracker/issues/496

**Pull request closed without merging**
