### PR TITLE
Dark mode colors

### PR DESCRIPTION
**Pull request by dfabulich**
# Tag Editor Before

image

# Tag Editor After

image

# Edit Link Before

image

# Edit Link After

image

### CODE REVIEW

**Comment by salty-horse** [comment]
Is the "Edit Link" box background supposed to be white? I'd expect it to be black like the page behind it, or a slightly lighter shade.

What about `textarea`s? In github, those have a dark background with gray text.

Github uses `#0d1117` instead of black for the background of the site, and text input boxes - I think it feels less oppressive.

**Comment by alice-blue** [comment]
Related to text areas in dark mode: https://github.com/iftechfoundation/ifdb-suggestion-tracker/issues/515

**Comment by dfabulich** [comment]
Yeah, there's definitely more available to fix here. I mostly just wanted to fix the illegible Help/Close/Cancel buttons and the heading color in the title bar of the popup. We can fix other stuff in future PRs.

**Comment by alice-blue** [comment]
Screenshots look ok to me (I did not open in codespace).

**Pull request merged**
