### PR TITLE
Rename "Your Inbox" -> "Inbox", "Your Activity" -> "My Activity"

### PR DESCRIPTION
**Pull request by dfabulich**
This just barely fits on an iPhone 12 Mini
simulator_screenshot_F3A0C51B-BCD7-4197-83E7-B3D402430190

### CODE REVIEW

**Comment by dfabulich** [comment]
@alice-blue I think we could bring back "Your Activity" if we got rid of "Home" as a text link…? The banner is clickable now.

**Comment by alice-blue** [comment]
"Your" vs. "my" isn't a big deal to me either way.

**Comment by alice-blue** [comment]
@dfabulich Are you planning to keep it as "my" or is that something that might change (if you take off "home")? I ask because I'm wondering if the headings on the activity page should change from "your" to "my" to be consistent.

**Comment by dfabulich** [comment]
I think the first thing to do is to make a hamburger menu. https://github.com/iftechfoundation/ifdb-suggestion-tracker/issues/252 Then, we'll have enough room to call it whatever we want.

**Pull request merged**
