### PR TITLE
Larger headers

### LINKED ISSUE #981: Make section headers bigger on the home page
Repeated calls for this on https://intfiction.org/t/an-idea-split-game-and-review-feeds-on-ifdb/66710

### PR DESCRIPTION
**Pull request by dfabulich**
Fixes #981

To get this to work, I had to move links out of the "Welcome to IFDB" section and into "New on IFDB" to prevent wrapping on mobile, and I had to remove "..." from "IFDB Recommends"

# Before

image

# After

image

### CODE REVIEW

**Comment by salty-horse** [comment]
On my local machine, this makes the "New on IFDB" header appears, and is empty.

BTW, unrelated to this, the background of the headers very faint, and I need to concentrate to see its boundaries over the white background.

**Comment by dfabulich** [comment]
Having the section appear blank is kinda by design.

On my first attempt, making "[-] Welcome to IFDB!" larger, alongside the "All Updates | Site News" links, caused the header to wrap to two lines in an ugly way.

The only way to make the header bigger was to move those links somewhere else. But where? I figured I'd move them to the "New on IFDB" section.

But what if there's no site news, competition, poll, or list within the last three days? Where would we put the links then?

And the only reasonable place I could think of was to keep them in the "New on IFDB" section, but leave the section present but empty when there's nothing new.

WDYT? Is there a better thing to do here?

**Comment by salty-horse** [comment]
One solution is to always show at least one news item, even if it's old.

**Comment by dfabulich** [comment]
I like it! Done.

**Pull request merged**
